services:
  react_env:
    build:
      context : .
      dockerfile : Dockerfile

    volumes:
      - ./apps:/home/ubuntu

    expose:
      - "5173"
      - "8000"

    ports:
      - "8000:8000" 
      - "5173:5173"
      - "8080:8080"

    stdin_open: true
    tty: true
